package com.futo.themestudiopro.data

import java.util.Locale

/**
 * يولّد theme.txt بصيغة FUTO Keyboard الرسمية (الإصدار 1.0).
 *
 * الميزات:
 *  - 44 لونًا مطلوبة
 *  - [options.font] للخط (إن وُجد)
 *  - [options.background] للخلفية (إن وُجدت)
 *  - [[matchrules.border]] لكل أصل
 *  - [[asset.border]] مع slicing/gap/padding
 */
object TomlGenerator {

    /**
     * يولّد theme.txt.
     *
     * @param theme الثيم الحالي
     * @param fontsList أسماء ملفات الخطوط في ZIP
     * @param hasBackground هل توجد صورة خلفية في ZIP
     * @param shapesList أسماء ملفات الأشكال في ZIP
     */
    fun generate(
        theme: ThemeData,
        fontsList: Set<String> = emptySet(),
        hasBackground: Boolean = false,
        shapesList: Set<String> = emptySet(),
    ): String {
        val sb = StringBuilder()

        // ═══════════ الترويسة ═══════════
        sb.appendLine("# FUTO Keyboard Theme Configuration")
        sb.appendLine("# Format version: 1.0")
        sb.appendLine("# Generated by Theme Studio Pro")
        sb.appendLine()

        // ═══════════ معلومات أساسية ═══════════
        sb.appendLine("name = \"${esc(theme.name)}\"")
        sb.appendLine("author = \"${esc(theme.author)}\"")
        sb.appendLine("id = \"${esc(theme.id)}\"")
        sb.appendLine("version = ${theme.version}")
        sb.appendLine("description = \"${esc(theme.description)}\"")
        sb.appendLine()

        // ═══════════ [options] ═══════════
        sb.appendLine("[options]")
        sb.appendLine("auto_borders = ${theme.autoBorders}")
        sb.appendLine("center_hints = ${theme.centerHints}")
        sb.appendLine("roundedness = ${n(theme.roundedness)}")
        sb.appendLine("scale_text = ${n(theme.scaleText)}")
        sb.appendLine("scale_hints = ${n(theme.scaleHints)}")
        sb.appendLine("weight_text = ${n(theme.weightText)}")
        sb.appendLine("weight_hints = ${n(theme.weightHints)}")
        sb.appendLine()

        // ═══════════ [options.font] ═══════════
        val fontName = theme.fontName ?: theme.arabicFontName
        if (fontName != null) {
            val actualName = if (fontName.endsWith(".ttf", true) || fontName.endsWith(".otf", true)) {
                fontName
            } else {
                "$fontName.ttf"
            }
            if (fontsList.contains(actualName) || fontsList.contains(fontName)) {
                val realName = if (fontsList.contains(actualName)) actualName else fontName
                sb.appendLine("[options.font]")
                sb.appendLine("font = \"${esc(realName)}\"")
                sb.appendLine()
            }
        }

        // ═══════════ [options.background] ═══════════
        if (hasBackground) {
            sb.appendLine("[options.background]")
            sb.appendLine("image = \"background.png\"")
            sb.appendLine("opacity = ${n(theme.backgroundOpacity)}")
            sb.appendLine("action_bar_opacity = ${n(theme.actionBarOpacity)}")
            sb.appendLine("cropping = [0.0, 0.0, 1.0, 1.0]")
            sb.appendLine()
        }

        // ═══════════ [colors] — 44 لونًا ═══════════
        sb.appendLine("[colors]")
        theme.allColorsForExport().forEach { (key, value) ->
            sb.appendLine("$key = \"${esc(value)}\"")
        }
        sb.appendLine()

        // ═══════════ matchrules + assets ═══════════
        val borderFiles = shapesList.filter { it.startsWith("Shapes/") || it.startsWith("Key-") }
        val iconFiles = shapesList.filter { it.startsWith("Icons/") }

        if (borderFiles.isNotEmpty()) {
            borderFiles.forEach { asset ->
                sb.appendLine("[[matchrules.border]]")
                sb.appendLine("selector = \"normal\"")
                sb.appendLine("asset = \"${esc(asset)}\"")
                sb.appendLine()
            }
        }

        if (iconFiles.isNotEmpty()) {
            iconFiles.forEach { asset ->
                sb.appendLine("[[matchrules.icon]]")
                sb.appendLine("selector = \"icon\"")
                sb.appendLine("asset = \"${esc(asset)}\"")
                sb.appendLine()
            }
        }

        // asset.border
        borderFiles.forEach { fname ->
            sb.appendLine("[[asset.border]]")
            sb.appendLine("name = \"${esc(fname)}\"")
            sb.appendLine("background_tint = \"#FFFFFFFF\"")
            sb.appendLine("foreground_tint = \"#FFFFFFFF\"")
            sb.appendLine("padding = [0, 0, 0, 0]")
            sb.appendLine("slicing = [0.300, 0.300, 0.700, 0.700]")
            sb.appendLine("gap = [1, 1, 1, 1]")
            sb.appendLine("target_density = 640")
            sb.appendLine()
        }

        // asset.icon
        iconFiles.forEach { fname ->
            sb.appendLine("[[asset.icon]]")
            sb.appendLine("name = \"${esc(fname)}\"")
            sb.appendLine("target_density = 640")
            sb.appendLine()
        }

        return sb.toString()
    }

    /**
     * تنسيق أرقام بصيغة إنجليزية (لتجنب الأرقام العربية في TOML).
     */
    private fun n(value: Float): String {
        return String.format(Locale.US, "%.3f", value)
    }

    /**
     * escape الاقتباسات.
     */
    private fun esc(text: String): String {
        return text
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", " ")
    }
}
